# -*- coding: utf-8 -*-
"""Another copy of Unemployment_analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PFz7S6lJT5GPDLavUqXeBmi1dd7u0Pro
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv('Unemployment_in_India.csv')

print(data.head())
print(data.info())

print(data['UnemploymentRate'].describe())

print("1. Display basic information about the dataset")
print("2. Describe the Unemployment Rate")
print("3. Plot the distribution of Unemployment Rate")


user_choice = input("Enter your choice (1, 2, or 3): ")

if user_choice == '1':
    print(data.head())
    print(data.info())
elif user_choice == '2':
    print(data['UnemploymentRate'].describe())
elif user_choice == '3':
    plt.figure(figsize=(10, 6))
    plt.hist(data['UnemploymentRate'], bins=20, edgecolor='black')
    plt.title('Distribution of Unemployment Rate')
    plt.xlabel('Unemployment Rate')
    plt.ylabel('Frequency')
    plt.show()
else:
    print("Invalid choice. Please enter 1, 2, or 3.")